### ISSUE TITLE
[FEATURE] Favicon image

### ISSUE THREAD

**Issue by Codedwells** [Codedwells/LCG#10]
A favicon image might be a good idea than having the generic globe icon.

- [ ] Favicon should be in assets folder
- [ ] Favicon should have a community theme

**Comment by Yashdon999** [comment]
Hey, I would like to work on this issue

**Comment by Codedwells** [comment]
> Hey, I would like to work on this issue
Would be great to have you contribute.

**Comment by Yashdon999** [comment]
sir May I put which photo in the Favicon 
can you tell me

**Comment by Codedwells** [comment]
> sir May I put which photo in the Favicon can you tell me

You can find any which suits a  coding theme.

**Comment by Yashdon999** [comment]
ok

**Comment by Pinaka-Pani-18** [comment]
Hi, I would like to contribute to this issue

**Comment by Codedwells** [comment]
> Hi, Can I know the issue is solved or not ? I would like to contribute to this issue.

It is yet to be solved you can give it a shot.
