### ISSUE TITLE
git commit command seems to be incorrect

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Codedwells/LCG#19]
**while using this below command:**

![git cz](https://user-images.githubusercontent.com/102857774/221422360-6306a069-a60f-4919-83ad-9593fa158cc5.png)

**I am getting like this:**

![git command](https://user-images.githubusercontent.com/102857774/221422358-b8131e4c-7aaf-4fb2-8566-48eed9fef599.png)

**Comment by Codedwells** [comment]
Sorry about that let me update the README
